# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aNxzwCS6EUJICgIN5BTRjRgSbtVpuzZ
"""

import steramlit as st
st.title("Welcome To The First Website Using Stremlit😊❤️")
name=st.text_input("Whats Your Name?😁")
if name:
  st.write("Welcome To The Website",name,"Nice To Meet You💕😊")
  st.ballons()